spring.application.name=Skillcheck

# 環境変数 DATABASE_URL があればそれを使用、なければローカル用を使用
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/skillcheck}

# 環境変数がない場合はローカル用の値を使用
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgrestest}

spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/QuestionMapper.xml
spring.sql.init.mode=always
