# 明示的に値を読み込ませる
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:/mapper/*.xml

spring.thymeleaf.cache=false

server.error.include-stacktrace=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

